version: '2'
services:
    captainslogapp-app:
        image: captainslogapp
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://captainslogapp-mysql:3306/captainslogapp?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8086:8086
    captainslogapp-mysql:
        extends:
            file: mysql.yml
            service: captainslogapp-mysql
